
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.1
 * Query Engine version: 55ae170b1ced7fc6ed07a15f110549408c501bb3
 */
Prisma.prismaVersion = {
  client: "7.4.1",
  engine: "55ae170b1ced7fc6ed07a15f110549408c501bb3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Admin_event_entityScalarFieldEnum = {
  id: 'id',
  admin_event_time: 'admin_event_time',
  realm_id: 'realm_id',
  operation_type: 'operation_type',
  auth_realm_id: 'auth_realm_id',
  auth_client_id: 'auth_client_id',
  auth_user_id: 'auth_user_id',
  ip_address: 'ip_address',
  resource_path: 'resource_path',
  representation: 'representation',
  error: 'error',
  resource_type: 'resource_type',
  details_json: 'details_json'
};

exports.Prisma.Associated_policyScalarFieldEnum = {
  policy_id: 'policy_id',
  associated_policy_id: 'associated_policy_id'
};

exports.Prisma.Authentication_executionScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  authenticator: 'authenticator',
  realm_id: 'realm_id',
  flow_id: 'flow_id',
  requirement: 'requirement',
  priority: 'priority',
  authenticator_flow: 'authenticator_flow',
  auth_flow_id: 'auth_flow_id',
  auth_config: 'auth_config'
};

exports.Prisma.Authentication_flowScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  description: 'description',
  realm_id: 'realm_id',
  provider_id: 'provider_id',
  top_level: 'top_level',
  built_in: 'built_in'
};

exports.Prisma.Authenticator_configScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  realm_id: 'realm_id'
};

exports.Prisma.Authenticator_config_entryScalarFieldEnum = {
  authenticator_id: 'authenticator_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Broker_linkScalarFieldEnum = {
  identity_provider: 'identity_provider',
  storage_provider_id: 'storage_provider_id',
  realm_id: 'realm_id',
  broker_user_id: 'broker_user_id',
  broker_username: 'broker_username',
  token: 'token',
  user_id: 'user_id'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  enabled: 'enabled',
  full_scope_allowed: 'full_scope_allowed',
  client_id: 'client_id',
  not_before: 'not_before',
  public_client: 'public_client',
  secret: 'secret',
  base_url: 'base_url',
  bearer_only: 'bearer_only',
  management_url: 'management_url',
  surrogate_auth_required: 'surrogate_auth_required',
  realm_id: 'realm_id',
  protocol: 'protocol',
  node_rereg_timeout: 'node_rereg_timeout',
  frontchannel_logout: 'frontchannel_logout',
  consent_required: 'consent_required',
  name: 'name',
  service_accounts_enabled: 'service_accounts_enabled',
  client_authenticator_type: 'client_authenticator_type',
  root_url: 'root_url',
  description: 'description',
  registration_token: 'registration_token',
  standard_flow_enabled: 'standard_flow_enabled',
  implicit_flow_enabled: 'implicit_flow_enabled',
  direct_access_grants_enabled: 'direct_access_grants_enabled',
  always_display_in_console: 'always_display_in_console'
};

exports.Prisma.Client_attributesScalarFieldEnum = {
  client_id: 'client_id',
  name: 'name',
  value: 'value'
};

exports.Prisma.Client_auth_flow_bindingsScalarFieldEnum = {
  client_id: 'client_id',
  flow_id: 'flow_id',
  binding_name: 'binding_name'
};

exports.Prisma.Client_initial_accessScalarFieldEnum = {
  id: 'id',
  realm_id: 'realm_id',
  timestamp: 'timestamp',
  expiration: 'expiration',
  count: 'count',
  remaining_count: 'remaining_count'
};

exports.Prisma.Client_node_registrationsScalarFieldEnum = {
  client_id: 'client_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Client_scopeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  realm_id: 'realm_id',
  description: 'description',
  protocol: 'protocol'
};

exports.Prisma.Client_scope_attributesScalarFieldEnum = {
  scope_id: 'scope_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Client_scope_clientScalarFieldEnum = {
  client_id: 'client_id',
  scope_id: 'scope_id',
  default_scope: 'default_scope'
};

exports.Prisma.Client_scope_role_mappingScalarFieldEnum = {
  scope_id: 'scope_id',
  role_id: 'role_id'
};

exports.Prisma.ComponentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parent_id: 'parent_id',
  provider_id: 'provider_id',
  provider_type: 'provider_type',
  realm_id: 'realm_id',
  sub_type: 'sub_type'
};

exports.Prisma.Component_configScalarFieldEnum = {
  id: 'id',
  component_id: 'component_id',
  name: 'name',
  value: 'value'
};

exports.Prisma.Composite_roleScalarFieldEnum = {
  composite: 'composite',
  child_role: 'child_role'
};

exports.Prisma.CredentialScalarFieldEnum = {
  id: 'id',
  salt: 'salt',
  type: 'type',
  user_id: 'user_id',
  created_date: 'created_date',
  user_label: 'user_label',
  secret_data: 'secret_data',
  credential_data: 'credential_data',
  priority: 'priority'
};

exports.Prisma.DatabasechangeloglockScalarFieldEnum = {
  id: 'id',
  locked: 'locked',
  lockgranted: 'lockgranted',
  lockedby: 'lockedby'
};

exports.Prisma.Default_client_scopeScalarFieldEnum = {
  realm_id: 'realm_id',
  scope_id: 'scope_id',
  default_scope: 'default_scope'
};

exports.Prisma.Event_entityScalarFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  details_json: 'details_json',
  error: 'error',
  ip_address: 'ip_address',
  realm_id: 'realm_id',
  session_id: 'session_id',
  event_time: 'event_time',
  type: 'type',
  user_id: 'user_id',
  details_json_long_value: 'details_json_long_value'
};

exports.Prisma.Fed_user_attributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id',
  value: 'value',
  long_value_hash: 'long_value_hash',
  long_value_hash_lower_case: 'long_value_hash_lower_case',
  long_value: 'long_value'
};

exports.Prisma.Fed_user_consentScalarFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id',
  created_date: 'created_date',
  last_updated_date: 'last_updated_date',
  client_storage_provider: 'client_storage_provider',
  external_client_id: 'external_client_id'
};

exports.Prisma.Fed_user_consent_cl_scopeScalarFieldEnum = {
  user_consent_id: 'user_consent_id',
  scope_id: 'scope_id'
};

exports.Prisma.Fed_user_credentialScalarFieldEnum = {
  id: 'id',
  salt: 'salt',
  type: 'type',
  created_date: 'created_date',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id',
  user_label: 'user_label',
  secret_data: 'secret_data',
  credential_data: 'credential_data',
  priority: 'priority'
};

exports.Prisma.Fed_user_group_membershipScalarFieldEnum = {
  group_id: 'group_id',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id'
};

exports.Prisma.Fed_user_required_actionScalarFieldEnum = {
  required_action: 'required_action',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id'
};

exports.Prisma.Fed_user_role_mappingScalarFieldEnum = {
  role_id: 'role_id',
  user_id: 'user_id',
  realm_id: 'realm_id',
  storage_provider_id: 'storage_provider_id'
};

exports.Prisma.Federated_identityScalarFieldEnum = {
  identity_provider: 'identity_provider',
  realm_id: 'realm_id',
  federated_user_id: 'federated_user_id',
  federated_username: 'federated_username',
  token: 'token',
  user_id: 'user_id'
};

exports.Prisma.Federated_userScalarFieldEnum = {
  id: 'id',
  storage_provider_id: 'storage_provider_id',
  realm_id: 'realm_id'
};

exports.Prisma.Group_attributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  value: 'value',
  group_id: 'group_id'
};

exports.Prisma.Group_role_mappingScalarFieldEnum = {
  role_id: 'role_id',
  group_id: 'group_id'
};

exports.Prisma.Identity_providerScalarFieldEnum = {
  internal_id: 'internal_id',
  enabled: 'enabled',
  provider_alias: 'provider_alias',
  provider_id: 'provider_id',
  store_token: 'store_token',
  authenticate_by_default: 'authenticate_by_default',
  realm_id: 'realm_id',
  add_token_role: 'add_token_role',
  trust_email: 'trust_email',
  first_broker_login_flow_id: 'first_broker_login_flow_id',
  post_broker_login_flow_id: 'post_broker_login_flow_id',
  provider_display_name: 'provider_display_name',
  link_only: 'link_only',
  organization_id: 'organization_id',
  hide_on_login: 'hide_on_login'
};

exports.Prisma.Identity_provider_configScalarFieldEnum = {
  identity_provider_id: 'identity_provider_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Identity_provider_mapperScalarFieldEnum = {
  id: 'id',
  name: 'name',
  idp_alias: 'idp_alias',
  idp_mapper_name: 'idp_mapper_name',
  realm_id: 'realm_id'
};

exports.Prisma.Idp_mapper_configScalarFieldEnum = {
  idp_mapper_id: 'idp_mapper_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Keycloak_groupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parent_group: 'parent_group',
  realm_id: 'realm_id',
  type: 'type'
};

exports.Prisma.Keycloak_roleScalarFieldEnum = {
  id: 'id',
  client_realm_constraint: 'client_realm_constraint',
  client_role: 'client_role',
  description: 'description',
  name: 'name',
  realm_id: 'realm_id',
  client: 'client',
  realm: 'realm'
};

exports.Prisma.Migration_modelScalarFieldEnum = {
  id: 'id',
  version: 'version',
  update_time: 'update_time'
};

exports.Prisma.Offline_client_sessionScalarFieldEnum = {
  user_session_id: 'user_session_id',
  client_id: 'client_id',
  offline_flag: 'offline_flag',
  timestamp: 'timestamp',
  data: 'data',
  client_storage_provider: 'client_storage_provider',
  external_client_id: 'external_client_id',
  version: 'version'
};

exports.Prisma.Offline_user_sessionScalarFieldEnum = {
  user_session_id: 'user_session_id',
  user_id: 'user_id',
  realm_id: 'realm_id',
  created_on: 'created_on',
  offline_flag: 'offline_flag',
  data: 'data',
  last_session_refresh: 'last_session_refresh',
  broker_session_id: 'broker_session_id',
  version: 'version'
};

exports.Prisma.OrgScalarFieldEnum = {
  id: 'id',
  enabled: 'enabled',
  realm_id: 'realm_id',
  group_id: 'group_id',
  name: 'name',
  description: 'description',
  alias: 'alias',
  redirect_url: 'redirect_url'
};

exports.Prisma.Org_domainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  verified: 'verified',
  org_id: 'org_id'
};

exports.Prisma.Policy_configScalarFieldEnum = {
  policy_id: 'policy_id',
  name: 'name',
  value: 'value'
};

exports.Prisma.Protocol_mapperScalarFieldEnum = {
  id: 'id',
  name: 'name',
  protocol: 'protocol',
  protocol_mapper_name: 'protocol_mapper_name',
  client_id: 'client_id',
  client_scope_id: 'client_scope_id'
};

exports.Prisma.Protocol_mapper_configScalarFieldEnum = {
  protocol_mapper_id: 'protocol_mapper_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.RealmScalarFieldEnum = {
  id: 'id',
  access_code_lifespan: 'access_code_lifespan',
  user_action_lifespan: 'user_action_lifespan',
  access_token_lifespan: 'access_token_lifespan',
  account_theme: 'account_theme',
  admin_theme: 'admin_theme',
  email_theme: 'email_theme',
  enabled: 'enabled',
  events_enabled: 'events_enabled',
  events_expiration: 'events_expiration',
  login_theme: 'login_theme',
  name: 'name',
  not_before: 'not_before',
  password_policy: 'password_policy',
  registration_allowed: 'registration_allowed',
  remember_me: 'remember_me',
  reset_password_allowed: 'reset_password_allowed',
  social: 'social',
  ssl_required: 'ssl_required',
  sso_idle_timeout: 'sso_idle_timeout',
  sso_max_lifespan: 'sso_max_lifespan',
  update_profile_on_soc_login: 'update_profile_on_soc_login',
  verify_email: 'verify_email',
  master_admin_client: 'master_admin_client',
  login_lifespan: 'login_lifespan',
  internationalization_enabled: 'internationalization_enabled',
  default_locale: 'default_locale',
  reg_email_as_username: 'reg_email_as_username',
  admin_events_enabled: 'admin_events_enabled',
  admin_events_details_enabled: 'admin_events_details_enabled',
  edit_username_allowed: 'edit_username_allowed',
  otp_policy_counter: 'otp_policy_counter',
  otp_policy_window: 'otp_policy_window',
  otp_policy_period: 'otp_policy_period',
  otp_policy_digits: 'otp_policy_digits',
  otp_policy_alg: 'otp_policy_alg',
  otp_policy_type: 'otp_policy_type',
  browser_flow: 'browser_flow',
  registration_flow: 'registration_flow',
  direct_grant_flow: 'direct_grant_flow',
  reset_credentials_flow: 'reset_credentials_flow',
  client_auth_flow: 'client_auth_flow',
  offline_session_idle_timeout: 'offline_session_idle_timeout',
  revoke_refresh_token: 'revoke_refresh_token',
  access_token_life_implicit: 'access_token_life_implicit',
  login_with_email_allowed: 'login_with_email_allowed',
  duplicate_emails_allowed: 'duplicate_emails_allowed',
  docker_auth_flow: 'docker_auth_flow',
  refresh_token_max_reuse: 'refresh_token_max_reuse',
  allow_user_managed_access: 'allow_user_managed_access',
  sso_max_lifespan_remember_me: 'sso_max_lifespan_remember_me',
  sso_idle_timeout_remember_me: 'sso_idle_timeout_remember_me',
  default_role: 'default_role'
};

exports.Prisma.Realm_attributeScalarFieldEnum = {
  name: 'name',
  realm_id: 'realm_id',
  value: 'value'
};

exports.Prisma.Realm_default_groupsScalarFieldEnum = {
  realm_id: 'realm_id',
  group_id: 'group_id'
};

exports.Prisma.Realm_enabled_event_typesScalarFieldEnum = {
  realm_id: 'realm_id',
  value: 'value'
};

exports.Prisma.Realm_events_listenersScalarFieldEnum = {
  realm_id: 'realm_id',
  value: 'value'
};

exports.Prisma.Realm_localizationsScalarFieldEnum = {
  realm_id: 'realm_id',
  locale: 'locale',
  texts: 'texts'
};

exports.Prisma.Realm_required_credentialScalarFieldEnum = {
  type: 'type',
  form_label: 'form_label',
  input: 'input',
  secret: 'secret',
  realm_id: 'realm_id'
};

exports.Prisma.Realm_smtp_configScalarFieldEnum = {
  realm_id: 'realm_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Realm_supported_localesScalarFieldEnum = {
  realm_id: 'realm_id',
  value: 'value'
};

exports.Prisma.Redirect_urisScalarFieldEnum = {
  client_id: 'client_id',
  value: 'value'
};

exports.Prisma.Required_action_configScalarFieldEnum = {
  required_action_id: 'required_action_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.Required_action_providerScalarFieldEnum = {
  id: 'id',
  alias: 'alias',
  name: 'name',
  realm_id: 'realm_id',
  enabled: 'enabled',
  default_action: 'default_action',
  provider_id: 'provider_id',
  priority: 'priority'
};

exports.Prisma.Resource_attributeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  value: 'value',
  resource_id: 'resource_id'
};

exports.Prisma.Resource_policyScalarFieldEnum = {
  resource_id: 'resource_id',
  policy_id: 'policy_id'
};

exports.Prisma.Resource_scopeScalarFieldEnum = {
  resource_id: 'resource_id',
  scope_id: 'scope_id'
};

exports.Prisma.Resource_serverScalarFieldEnum = {
  id: 'id',
  allow_rs_remote_mgmt: 'allow_rs_remote_mgmt',
  policy_enforce_mode: 'policy_enforce_mode',
  decision_strategy: 'decision_strategy'
};

exports.Prisma.Resource_server_perm_ticketScalarFieldEnum = {
  id: 'id',
  owner: 'owner',
  requester: 'requester',
  created_timestamp: 'created_timestamp',
  granted_timestamp: 'granted_timestamp',
  resource_id: 'resource_id',
  scope_id: 'scope_id',
  resource_server_id: 'resource_server_id',
  policy_id: 'policy_id'
};

exports.Prisma.Resource_server_policyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  type: 'type',
  decision_strategy: 'decision_strategy',
  logic: 'logic',
  resource_server_id: 'resource_server_id',
  owner: 'owner'
};

exports.Prisma.Resource_server_resourceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  icon_uri: 'icon_uri',
  owner: 'owner',
  resource_server_id: 'resource_server_id',
  owner_managed_access: 'owner_managed_access',
  display_name: 'display_name'
};

exports.Prisma.Resource_server_scopeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon_uri: 'icon_uri',
  resource_server_id: 'resource_server_id',
  display_name: 'display_name'
};

exports.Prisma.Resource_urisScalarFieldEnum = {
  resource_id: 'resource_id',
  value: 'value'
};

exports.Prisma.Revoked_tokenScalarFieldEnum = {
  id: 'id',
  expire: 'expire'
};

exports.Prisma.Role_attributeScalarFieldEnum = {
  id: 'id',
  role_id: 'role_id',
  name: 'name',
  value: 'value'
};

exports.Prisma.Scope_mappingScalarFieldEnum = {
  client_id: 'client_id',
  role_id: 'role_id'
};

exports.Prisma.Scope_policyScalarFieldEnum = {
  scope_id: 'scope_id',
  policy_id: 'policy_id'
};

exports.Prisma.User_attributeScalarFieldEnum = {
  name: 'name',
  value: 'value',
  user_id: 'user_id',
  id: 'id',
  long_value_hash: 'long_value_hash',
  long_value_hash_lower_case: 'long_value_hash_lower_case',
  long_value: 'long_value'
};

exports.Prisma.User_consentScalarFieldEnum = {
  id: 'id',
  client_id: 'client_id',
  user_id: 'user_id',
  created_date: 'created_date',
  last_updated_date: 'last_updated_date',
  client_storage_provider: 'client_storage_provider',
  external_client_id: 'external_client_id'
};

exports.Prisma.User_consent_client_scopeScalarFieldEnum = {
  user_consent_id: 'user_consent_id',
  scope_id: 'scope_id'
};

exports.Prisma.User_entityScalarFieldEnum = {
  id: 'id',
  email: 'email',
  email_constraint: 'email_constraint',
  email_verified: 'email_verified',
  enabled: 'enabled',
  federation_link: 'federation_link',
  first_name: 'first_name',
  last_name: 'last_name',
  realm_id: 'realm_id',
  username: 'username',
  created_timestamp: 'created_timestamp',
  service_account_client_link: 'service_account_client_link',
  not_before: 'not_before'
};

exports.Prisma.User_federation_configScalarFieldEnum = {
  user_federation_provider_id: 'user_federation_provider_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.User_federation_mapperScalarFieldEnum = {
  id: 'id',
  name: 'name',
  federation_provider_id: 'federation_provider_id',
  federation_mapper_type: 'federation_mapper_type',
  realm_id: 'realm_id'
};

exports.Prisma.User_federation_mapper_configScalarFieldEnum = {
  user_federation_mapper_id: 'user_federation_mapper_id',
  value: 'value',
  name: 'name'
};

exports.Prisma.User_federation_providerScalarFieldEnum = {
  id: 'id',
  changed_sync_period: 'changed_sync_period',
  display_name: 'display_name',
  full_sync_period: 'full_sync_period',
  last_sync: 'last_sync',
  priority: 'priority',
  provider_name: 'provider_name',
  realm_id: 'realm_id'
};

exports.Prisma.User_group_membershipScalarFieldEnum = {
  group_id: 'group_id',
  user_id: 'user_id',
  membership_type: 'membership_type'
};

exports.Prisma.User_required_actionScalarFieldEnum = {
  user_id: 'user_id',
  required_action: 'required_action'
};

exports.Prisma.User_role_mappingScalarFieldEnum = {
  role_id: 'role_id',
  user_id: 'user_id'
};

exports.Prisma.Web_originsScalarFieldEnum = {
  client_id: 'client_id',
  value: 'value'
};

exports.Prisma.Jgroups_pingScalarFieldEnum = {
  address: 'address',
  name: 'name',
  cluster_name: 'cluster_name',
  ip: 'ip',
  coord: 'coord'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  admin_event_entity: 'admin_event_entity',
  associated_policy: 'associated_policy',
  authentication_execution: 'authentication_execution',
  authentication_flow: 'authentication_flow',
  authenticator_config: 'authenticator_config',
  authenticator_config_entry: 'authenticator_config_entry',
  broker_link: 'broker_link',
  client: 'client',
  client_attributes: 'client_attributes',
  client_auth_flow_bindings: 'client_auth_flow_bindings',
  client_initial_access: 'client_initial_access',
  client_node_registrations: 'client_node_registrations',
  client_scope: 'client_scope',
  client_scope_attributes: 'client_scope_attributes',
  client_scope_client: 'client_scope_client',
  client_scope_role_mapping: 'client_scope_role_mapping',
  component: 'component',
  component_config: 'component_config',
  composite_role: 'composite_role',
  credential: 'credential',
  databasechangeloglock: 'databasechangeloglock',
  default_client_scope: 'default_client_scope',
  event_entity: 'event_entity',
  fed_user_attribute: 'fed_user_attribute',
  fed_user_consent: 'fed_user_consent',
  fed_user_consent_cl_scope: 'fed_user_consent_cl_scope',
  fed_user_credential: 'fed_user_credential',
  fed_user_group_membership: 'fed_user_group_membership',
  fed_user_required_action: 'fed_user_required_action',
  fed_user_role_mapping: 'fed_user_role_mapping',
  federated_identity: 'federated_identity',
  federated_user: 'federated_user',
  group_attribute: 'group_attribute',
  group_role_mapping: 'group_role_mapping',
  identity_provider: 'identity_provider',
  identity_provider_config: 'identity_provider_config',
  identity_provider_mapper: 'identity_provider_mapper',
  idp_mapper_config: 'idp_mapper_config',
  keycloak_group: 'keycloak_group',
  keycloak_role: 'keycloak_role',
  migration_model: 'migration_model',
  offline_client_session: 'offline_client_session',
  offline_user_session: 'offline_user_session',
  org: 'org',
  org_domain: 'org_domain',
  policy_config: 'policy_config',
  protocol_mapper: 'protocol_mapper',
  protocol_mapper_config: 'protocol_mapper_config',
  realm: 'realm',
  realm_attribute: 'realm_attribute',
  realm_default_groups: 'realm_default_groups',
  realm_enabled_event_types: 'realm_enabled_event_types',
  realm_events_listeners: 'realm_events_listeners',
  realm_localizations: 'realm_localizations',
  realm_required_credential: 'realm_required_credential',
  realm_smtp_config: 'realm_smtp_config',
  realm_supported_locales: 'realm_supported_locales',
  redirect_uris: 'redirect_uris',
  required_action_config: 'required_action_config',
  required_action_provider: 'required_action_provider',
  resource_attribute: 'resource_attribute',
  resource_policy: 'resource_policy',
  resource_scope: 'resource_scope',
  resource_server: 'resource_server',
  resource_server_perm_ticket: 'resource_server_perm_ticket',
  resource_server_policy: 'resource_server_policy',
  resource_server_resource: 'resource_server_resource',
  resource_server_scope: 'resource_server_scope',
  resource_uris: 'resource_uris',
  revoked_token: 'revoked_token',
  role_attribute: 'role_attribute',
  scope_mapping: 'scope_mapping',
  scope_policy: 'scope_policy',
  user_attribute: 'user_attribute',
  user_consent: 'user_consent',
  user_consent_client_scope: 'user_consent_client_scope',
  user_entity: 'user_entity',
  user_federation_config: 'user_federation_config',
  user_federation_mapper: 'user_federation_mapper',
  user_federation_mapper_config: 'user_federation_mapper_config',
  user_federation_provider: 'user_federation_provider',
  user_group_membership: 'user_group_membership',
  user_required_action: 'user_required_action',
  user_role_mapping: 'user_role_mapping',
  web_origins: 'web_origins',
  jgroups_ping: 'jgroups_ping'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
